### ISSUE TITLE
The performance of LSTM and ResNet

### ISSUE THREAD

**Issue by Scarecrow0** [horsepurve/DeepRTplus#9]
Hi! 
Thanks for your interesting work and the nice codebase!
I would like to know the performance of the ResNet and LSTM models on the HeLa and Yeast dataset. The paper seems only releases the Pearson r^2 results.  
Could you please inform me about the delta t95 of those two baseline models?

Thx!

**Comment by horsepurve** [comment]
Hi,

In terms of the Pearson, delta t95, and RMSE scores, please see Table S1, S2 for the HeLa data and S9 for the DIA data in the following excel file:
[sup-tables.xlsx](https://github.com/horsepurve/DeepRTplus/files/4367154/sup-tables.xlsx)
you can also find the detail of the two models at:
https://arxiv.org/abs/1711.00045

**Comment by Scarecrow0** [comment]
Thanks a lot!
